Making sure everything is added.  Need to fix the man file maker.

diff --git a/doc/Makefile.in b/doc/Makefile.in
--- a/doc/Makefile.in
+++ b/doc/Makefile.in
@@ -15,8 +15,6 @@
 
 @SET_MAKE@
 
-# makefile.am for resources
-
 VPATH = @srcdir@
 am__make_dryrun = \
   { \
@@ -53,8 +51,9 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-subdir = resources
-DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
+subdir = doc
+DIST_COMMON = $(dist_doc_DATA) $(dist_man_MANS) $(srcdir)/Makefile.am \
+	$(srcdir)/Makefile.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/ac-aux/m4/libtool.m4 \
 	$(top_srcdir)/ac-aux/m4/ltoptions.m4 \
@@ -103,8 +102,11 @@ am__uninstall_files_from_dir = { \
     || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
          $(am__cd) "$$dir" && rm -f $$files; }; \
   }
-am__installdirs = "$(DESTDIR)$(pkgdatadir)"
-DATA = $(pkgdata_DATA)
+man1dir = $(mandir)/man1
+am__installdirs = "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(docdir)"
+NROFF = nroff
+MANS = $(dist_man_MANS)
+DATA = $(dist_doc_DATA)
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 ACLOCAL = @ACLOCAL@
 AMTAR = @AMTAR@
@@ -120,7 +122,7 @@ CFLAGS = @CFLAGS@
 CPP = @CPP@
 CPPFLAGS = @CPPFLAGS@
 CYGPATH_W = @CYGPATH_W@
-DEFS = @DEFS@ @DEV_DEF@ -DLOCALEDIR=\"$(localedir)\"
+DEFS = @DEFS@
 DEPDIR = @DEPDIR@
 DEV_DEF = @DEV_DEF@
 DEV_LIB = @DEV_LIB@
@@ -202,10 +204,6 @@ build_cpu = @build_cpu@
 build_os = @build_os@
 build_vendor = @build_vendor@
 builddir = @builddir@
-
-# uses gencmn to build the resource data
-# gencmn can also make a C header, thus:
-# gencmn --name oly_lang -t dat -S fortune_resources.c fortune_resources.txt 
 datadir = @datadir@
 datarootdir = @datarootdir@
 docdir = @docdir@
@@ -239,41 +237,52 @@ target_alias = @target_alias@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-.PHONY = clean-local-res
-SUFFIXES = .res 
+MAINTAINERCLEANFILES = maintainer-clean-local $(HTMLPAGES)
+CLEANFILES = $(HTMLPAGES)
+DISTCLEANFILES = $(WIKIPAGES)
+SUFFIXES = .wiki
+TXTFILES = index.txt \
+												input_doc.txt \
+												inline_in_automake.txt \
+												bibliography.txt
 
-# Resource shortname
-RESNAME = oly_lang
-RESLIST = $(RESNAME).txt
-RESDIR = $(top_srcdir)/resources
-RESTEXT = root.txt \
-													en.txt \
-													el_GR.txt \
-													ja.txt
+WIKIPAGES = $(TXTFILES:txt=wiki)
+HTMLPAGES = $(TXTFILES:txt=html)
+adoc_icons_dir = /doc/tip/doc/icons	
+adoc_images_dir = /doc/tip/doc/images
+ASCIIDOC = asciidoc
+ADOC_REVISION = "`fossil finfo --limit 1 -b $< | \
+								grep -o '^[0-9a-fA-F]*'`"
 
-RESFILES = $(RESTEXT:txt=res)
-RESLDFLAGS = -L$(RESDIR) -l$(RESNAME)
-PKGDATAOPTS = -v -d . --tempdir .deps -e $(RESNAME)
-LINK.cc = $(CC) $(CFLAGS) $(LDFLAGS)
-GENRBOPT = -v --bundle-name $(RESNAME)
-pkgdata_DATA = oly_lang.dat
+ADOC_REVDATE = "`fossil finfo --limit 1 -b $< | \
+								grep -o '[0-9]*-[0-9]*-[0-9]*'`"
 
-# liboly_lang.a: $(RESFILES) $(RESLIST)
-#	mkdir -p .deps
-#	$(PKGDATA) --name $(RESNAME) --mode static $(PKGDATAOPTS) $(RESLIST)
+ADOCFLAGS = -a email=@FAQ_ADDR@ \
+												-a website=@PACKAGE_URL@ \
+												-a iconsdir=$(adoc_icons_dir) \
+												-a imagesdir=$(adoc_images_dir) \
+												-a revdate=$(ADOC_REVDATE) \
+												-a 'newline=\n' \
+												-a revision=$(ADOC_REVISION) \
+												--conf-file conf/fossil.conf
 
-#	$(LINK.cc) $^ $(LOADLIBES) $(LDLIBS) -o $@ $(XTRALIBS)
-# gencmn --name $(RESNAME) -t dat 0 $(RESLIST)
-CLEANFILES = $(RESFILES) \
-													$(RESLIST) \
-													$(RESTARGET) \
-													$(RESNAME).dat \
-													$(RESNAME)_dat.s 
+HTMLFLAGS = -a email=@FAQ_ADDR@ \
+												-a website=@PACKAGE_URL@ \
+												-a iconsdir=icons \
+												-a imagesdir=images \
+												-a data-uri \
+												-a revdate=$(ADOC_REVDATE) \
+												-a revision=$(ADOC_REVISION) \
+												--conf-file conf/asciidoc.conf
 
+AD1 = a2x
+dist_man_MANS = man/reverse.1
+dist_doc_DATA = $(HTMLPAGES)
+EXTRA_DIST = $(TXTFILES)
 all: all-am
 
 .SUFFIXES:
-.SUFFIXES: .res .txt
+.SUFFIXES: .wiki .1 .html .txt
 $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
@@ -283,9 +292,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
 	      exit 1;; \
 	  esac; \
 	done; \
-	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu resources/Makefile'; \
+	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu doc/Makefile'; \
 	$(am__cd) $(top_srcdir) && \
-	  $(AUTOMAKE) --gnu resources/Makefile
+	  $(AUTOMAKE) --gnu doc/Makefile
 .PRECIOUS: Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@case '$?' in \
@@ -310,27 +319,70 @@ mostlyclean-libtool:
 
 clean-libtool:
 	-rm -rf .libs _libs
-install-pkgdataDATA: $(pkgdata_DATA)
+install-man1: $(dist_man_MANS)
 	@$(NORMAL_INSTALL)
-	@list='$(pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
+	@list1=''; \
+	list2='$(dist_man_MANS)'; \
+	test -n "$(man1dir)" \
+	  && test -n "`echo $$list1$$list2`" \
+	  || exit 0; \
+	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
+	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
+	{ for i in $$list1; do echo "$$i"; done;  \
+	if test -n "$$list2"; then \
+	  for i in $$list2; do echo "$$i"; done \
+	    | sed -n '/\.1[a-z]*$$/p'; \
+	fi; \
+	} | while read p; do \
+	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	  echo "$$d$$p"; echo "$$p"; \
+	done | \
+	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
+	sed 'N;N;s,\n, ,g' | { \
+	list=; while read file base inst; do \
+	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
+	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
+	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
+	  fi; \
+	done; \
+	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
+	while read files; do \
+	  test -z "$$files" || { \
+	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
+	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
+	done; }
+
+uninstall-man1:
+	@$(NORMAL_UNINSTALL)
+	@list=''; test -n "$(man1dir)" || exit 0; \
+	files=`{ for i in $$list; do echo "$$i"; done; \
+	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
+	  sed -n '/\.1[a-z]*$$/p'; \
+	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
+	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
+install-dist_docDATA: $(dist_doc_DATA)
+	@$(NORMAL_INSTALL)
+	@list='$(dist_doc_DATA)'; test -n "$(docdir)" || list=; \
 	if test -n "$$list"; then \
-	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgdatadir)'"; \
-	  $(MKDIR_P) "$(DESTDIR)$(pkgdatadir)" || exit 1; \
+	  echo " $(MKDIR_P) '$(DESTDIR)$(docdir)'"; \
+	  $(MKDIR_P) "$(DESTDIR)$(docdir)" || exit 1; \
 	fi; \
 	for p in $$list; do \
 	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
 	  echo "$$d$$p"; \
 	done | $(am__base_list) | \
 	while read files; do \
-	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgdatadir)'"; \
-	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgdatadir)" || exit $$?; \
+	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(docdir)'"; \
+	  $(INSTALL_DATA) $$files "$(DESTDIR)$(docdir)" || exit $$?; \
 	done
 
-uninstall-pkgdataDATA:
+uninstall-dist_docDATA:
 	@$(NORMAL_UNINSTALL)
-	@list='$(pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
+	@list='$(dist_doc_DATA)'; test -n "$(docdir)" || list=; \
 	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
-	dir='$(DESTDIR)$(pkgdatadir)'; $(am__uninstall_files_from_dir)
+	dir='$(DESTDIR)$(docdir)'; $(am__uninstall_files_from_dir)
 tags: TAGS
 TAGS:
 
@@ -339,6 +391,19 @@ CTAGS:
 
 
 distdir: $(DISTFILES)
+	@list='$(MANS)'; if test -n "$$list"; then \
+	  list=`for p in $$list; do \
+	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
+	  if test -n "$$list" && \
+	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
+	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
+	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
+	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
+	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
+	    exit 1; \
+	  else :; fi; \
+	else :; fi
 	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	list='$(DISTFILES)'; \
@@ -370,9 +435,9 @@ distdir: $(DISTFILES)
 	done
 check-am: all-am
 check: check-am
-all-am: Makefile $(DATA)
+all-am: Makefile $(MANS) $(DATA)
 installdirs:
-	for dir in "$(DESTDIR)$(pkgdatadir)"; do \
+	for dir in "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(docdir)"; do \
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: install-am
@@ -402,13 +467,15 @@ clean-generic:
 distclean-generic:
 	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
 	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
+	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
 
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
+	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
 clean: clean-am
 
-clean-am: clean-generic clean-libtool clean-local mostlyclean-am
+clean-am: clean-generic clean-libtool mostlyclean-am
 
 distclean: distclean-am
 	-rm -f Makefile
@@ -418,15 +485,13 @@ dvi: dvi-am
 
 dvi-am:
 
-html: html-am
-
 html-am:
 
 info: info-am
 
 info-am:
 
-install-data-am: install-pkgdataDATA
+install-data-am: install-dist_docDATA install-man
 
 install-dvi: install-dvi-am
 
@@ -442,7 +507,7 @@ install-info: install-info-am
 
 install-info-am:
 
-install-man:
+install-man: install-man1
 
 install-pdf: install-pdf-am
 
@@ -456,7 +521,8 @@ installcheck-am:
 
 maintainer-clean: maintainer-clean-am
 	-rm -f Makefile
-maintainer-clean-am: distclean-am maintainer-clean-generic
+maintainer-clean-am: distclean-am maintainer-clean-generic \
+	maintainer-clean-local
 
 mostlyclean: mostlyclean-am
 
@@ -470,50 +536,53 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-pkgdataDATA
+uninstall-am: uninstall-dist_docDATA uninstall-man
+
+uninstall-man: uninstall-man1
 
 .MAKE: install-am install-strip
 
 .PHONY: all all-am check check-am clean clean-generic clean-libtool \
-	clean-local distclean distclean-generic distclean-libtool \
-	distclean-local distdir dvi dvi-am html html-am info info-am \
-	install install-am install-data install-data-am install-dvi \
-	install-dvi-am install-exec install-exec-am install-html \
-	install-html-am install-info install-info-am install-man \
-	install-pdf install-pdf-am install-pkgdataDATA install-ps \
+	distclean distclean-generic distclean-libtool distclean-local \
+	distdir dvi dvi-am html html-am info info-am install \
+	install-am install-data install-data-am install-dist_docDATA \
+	install-dvi install-dvi-am install-exec install-exec-am \
+	install-html install-html-am install-info install-info-am \
+	install-man install-man1 install-pdf install-pdf-am install-ps \
 	install-ps-am install-strip installcheck installcheck-am \
 	installdirs maintainer-clean maintainer-clean-generic \
-	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
-	ps ps-am uninstall uninstall-am uninstall-pkgdataDATA
+	maintainer-clean-local mostlyclean mostlyclean-generic \
+	mostlyclean-libtool pdf pdf-am ps ps-am uninstall uninstall-am \
+	uninstall-dist_docDATA uninstall-man uninstall-man1
 
 
-.txt.res:
-	@echo "generating $@"
-	$(GENRB) $(GENRBOPT) $^ -d $(RESDIR)
+.PHONY: html htmlrebuild wikirebuild atool-clean wiki
 
-root.res:
-	@echo "generating $@"
-	$(GENRB) $(GENRBOPT) $^ -d $(RESDIR) $(RESTEXT)
+wikirebuild:
+	rm -f $(WIKIPAGES)
 
-$(RESLIST): $(RESFILES)
-	ls *.res > $@
+wiki: wikirebuild $(WIKIPAGES)
 
-# $(GENRB) $(GENRBOPT) $^ -d $(RESDIR) $(RESFILES)
+htmlrebuild:
+	rm -f $(HTMLPAGES)
 
-# gencmn can generate a .dat file too using these commands
-oly_lang.dat: $(RESFILES) $(RESLIST)
-	mkdir -p .deps
-	$(PKGDATA) --name $(RESNAME) --mode common $(PKGDATAOPTS) $(RESLIST)
+html: htmlrebuild $(HTMLPAGES)
 
-clean-local-res:
-	rm -rf .deps
+maintainer-clean-local: wiki htmlrebuild
 
-clean-local: clean-local-res
+distclean-local: html
 
-distclean-local: clean-local 
+atool-clean: 
+		rm -rf Makefile.in Makefile
 
-$(TARGET): $(OBJECTS)
-	$(LINK.cc) $^ $(LOADLIBES) $(LDLIBS) -o $@ $(XTRALIBS)
+.txt.1:
+	$(AD1) --doctype=manpage --format=manpage $<
+
+.txt.wiki:
+	$(ASCIIDOC) --doctype article $(ADOCFLAGS) -o $@ $<
+
+.txt.html: 
+	$(ASCIIDOC) --backend html5 --doctype article $(HTMLFLAGS) -o $@ $<
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
